const language = {
  English: {
    "Cargo Details": "Please enter the details of your cargo shipment.",
    "Unloading Postcode": "Enter postcode",
    "Import or Export": "Import or Export",
    "Unloading Country": "DE",
    Dimensions: "Length x Width x Height in cm",
    Weight: "0",
    "Number of Pallets": "0",
    Submit: "Submit",
  },
  Dutch: {
    "Vracht details": "Voer de details van uw zending in.",
    "Postcode vanaf": "12341",
    "Postcode naar": "46000",
    "Land van afkomst": "NL",
    "Land van bestemming": "IT",
    Afmetingen: "100 x 100 x 30",
    Gewicht: "90",
    "Aantal pallets": "0",
    "Vaste toeslagen (voor speciale vereisten)": "",
    Transporteur: "Dsv",
    "Max gewicht": "729.17",
    Tarief: "161.02",
    Wegenbelasting: "2.67",
    Brandstoftoeslag: "1.08",
    "Totale kosten": "177.00",
    "Transporteur 2": "NTGRoad",
    "Max gewicht 2": "625.00",
    "Tarief 2": "186.48",
    "Wegenbelasting 2": "0.00",
    "Brandstoftoeslag 2": "1.06",
    "Totale kosten 2": "198.00",
  },
};
